//         DRAWING MATERIAL
//         "oil",
//         "pastel",
//         "oil pastel",
//         "watercolor",
//         "acrylic",
//         "pencil",
//         "graphite",
//         "colored pencil",
//         "charcoal",
//         "pencil and chalk",
//         "mono print",
//         "ink",
//         "pen and ink",
//         "reed and ink",
//         "crayon",
//         "mix media",
//         "clay",
//         "clay and wool",
//         "clear tape sculpture",
//         "acrylic collage",
//         "print",
//         "",
//
//         SUPPORT
// "canvas",
// "paper",
// "card stock",
// "vellum",
// "fabric",
// "stone",
// "wood",
// "metal",
// "fiber cloth",
// "wool felt",
// "tape",
// "canvas board",
// "board",
// "paper/matted",
// "",
